CREATE USER ebwtuition
IDENTIFIED BY pass
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to ebwtuition;
GRANT resource to ebwtuition;
GRANT create session TO ebwtuition;
GRANT create table TO ebwtuition;
GRANT create view TO ebwtuition;



conn ebwtuition/pass

CREATE TABLE EMP(
ID_NUM INTEGER PRIMARY KEY,
PASS VARCHAR2(50),
F_NAME VARCHAR2(50),
L_NAME VARCHAR2(50),
AMT_LEFT INTEGER
);

CREATE TABLE TRMS2(

U_NAME VARCHAR2 (50),
F_NAME VARCHAR2(50),
L_NAME VARCHAR2(50),
CLASS_TYPE VARCHAR2(50),
CLASS_COST INTEGER,
CLASS_GRADE VARCHAR2(50),
DESCRIPT VARCHAR2(500),
CLASS_START DATE,
FORM_ID INTEGER PRIMARY KEY,
APP_CODE1 INTEGER,
APP_CODE2 INTEGER,
APP_CODE3 INTEGER
);

INSERT INTO EMP VALUES (100, 'pass', 'John', 'Smith', 1000);
INSERT INTO EMP VALUES (200, 'pass', 'Brady', 'Wilson', 1000);
INSERT INTO EMP VALUES (300, 'pass', 'Julie', 'Hines', 1000);
INSERT INTO EMP VALUES (400, 'pass', 'Leslie', 'Waller', 1000);
INSERT INTO EMP VALUES (500, 'pass', 'Elliott', 'Bailey-Wills', 1000);
COMMIT;

CREATE TABLE EMP2(
USER_NAME VARCHAR2(50) PRIMARY KEY,
PASS VARCHAR2(50),
F_NAME VARCHAR2(50),
L_NAME VARCHAR2(50),
AMT_LEFT INTEGER
);

INSERT INTO EMP2 VALUES ('JS', 'pass', 'John', 'Smith', 1000);
COMMIT;

DROP TABLE REIMB;

CREATE TABLE SUPER2(
USER_NAME VARCHAR2(50)PRIMARY KEY,
PASS VARCHAR2(50),
F_NAME VARCHAR2(50),
L_NAME VARCHAR2(50),
AMT_LEFT INTEGER
);

CREATE TABLE DEP_HEAD2(
USER_NAME VARCHAR2(50)PRIMARY KEY,
PASS VARCHAR2(50),
F_NAME VARCHAR2(50),
L_NAME VARCHAR2(50),
AMT_LEFT INTEGER
);

CREATE TABLE BENCO2(
USER_NAME VARCHAR2(50)PRIMARY KEY,
PASS VARCHAR2(50),
F_NAME VARCHAR2(50),
L_NAME VARCHAR2(50),
AMT_LEFT INTEGER
);

CREATE TABLE OVERLORD2(
USER_NAME VARCHAR2(50)PRIMARY KEY,
PASS VARCHAR2(50),
F_NAME VARCHAR2(50),
L_NAME VARCHAR2(50),
AMT_LEFT INTEGER
);

INSERT INTO SUPER2 VALUES ('BW', 'pass', 'Brady', 'Wilson', 1000);



